name: All the Tech Things
description: Blog about all the tech things that inspire me.

url: "nyghtowl.io"
baseurl: /nyghtowl.io

paginate: 10

source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts

markdown: redcarpet
permalink: pretty
pygments: true
timezone: America/Los_Angeles

