name: All the Tech Things
description: blog about all the tech things

url: "nyghtowl.io"

paginate: 10

source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts

markdown: redcarpet
permalink: pretty
pygments: true
timezone: America/Los_Angeles


